name: Build Light Voice Changer EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Single EXE File
      run: |
        pyinstaller --noconfirm --onefile --windowed --name="LightVoiceChanger" main.py

    - name: Upload Built EXE
      uses: actions/upload-artifact@v4
      with:
        name: VoiceChanger-Windows-EXE
        path: dist/LightVoiceChanger.exe
        
