name: Build Pro Voice Changer

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: EXE Derle
        run: |
          pyinstaller --noconfirm --onefile --windowed --hidden-import="torch" --name="ProVoiceChanger" main.py

      - name: Çıktıyı Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: ProVoiceChanger
          path: dist/ProVoiceChanger.exe
          
